version: '3.8'
services:
  eurekaserver:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka

  sharedto:
    build:
      context: ./shared-dto
      dockerfile: Dockerfile
    container_name: dtos

  accountservice:
    build:
      context: ./accountservice
      dockerfile: Dockerfile
    container_name: accountservice
    depends_on:
      - sharedto
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/accountServiceDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka
  addressservice:
    build:
      context: ./addressservice
      dockerfile: Dockerfile
    container_name: addressservice
    depends_on:
      - sharedto
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/addressServiceDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka
  authservice:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: authservice
    depends_on:
      - sharedto
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/userServiceDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka
  customerservice:
    build:
      context: ./customerservice
      dockerfile: Dockerfile
    container_name: customerservice
    depends_on:
      - sharedto
      - eurekaserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/customerServiceDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka
  transactionservice:
    build:
      context: ./transactionservice
      dockerfile: Dockerfile
    container_name: transactionservice
    depends_on:
      - eurekaserver
      - sharedto
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/transactionServiceDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123321
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka

volumes:
  mysql_data: