spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/**
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/v1/address/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transaction/**
      discovery:
        locator:
          enabled: true

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
